# Generated by Django 4.2.4 on 2023-12-13 15:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='award_description',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='score',
        ),
        migrations.AddField(
            model_name='usercontest',
            name='distinction',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usercontest',
            name='medal',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usercontest',
            name='score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='deadline',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
